# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0002_auto_20170503_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='option_Stars',
            field=models.IntegerField(default=0),
        ),
    ]
