# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0004_auto_20170504_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
