# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0005_auto_20170504_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_weighted', models.DateTimeField(auto_now_add=True)),
                ('initial_weight', models.FloatField(editable=False, help_text='This will not change once added')),
                ('weight_today', models.FloatField(help_text='Enter new weight')),
                ('client_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='weighin',
            name='client_pk',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='WeighIn',
        ),
    ]
