# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0006_auto_20170504_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightin',
            name='initial_weight',
        ),
        migrations.AddField(
            model_name='client',
            name='initial_weight',
            field=models.FloatField(default=0, editable=False, help_text='This will not change once added'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(editable=False, max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
