# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 05:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0007_auto_20170504_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('option_Stars', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='client',
            name='initial_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weightin',
            name='date_weighted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weightin',
            name='weight_today',
            field=models.FloatField(),
        ),
    ]
