# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0008_auto_20170506_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
