# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0009_auto_20170507_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightin',
            name='client_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.Client'),
        ),
    ]
