# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0012_auto_20170507_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
