# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0013_auto_20170508_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-first_name']},
        ),
        migrations.RenameField(
            model_name='weightin',
            old_name='weight_today',
            new_name='weight',
        ),
    ]
