# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0014_auto_20170509_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('s', 'Saturday'), ('su', 'Sunday')], default='d', help_text='Days availability', max_length=2)),
                ('client_pk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.Client')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainingApp.WeightIn')),
            ],
        ),
    ]
