# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0015_workoutschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutschedule',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='time_of_day',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='weightin',
            name='date_weighted',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='weightin',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='workoutschedule',
            name='schedule',
            field=models.CharField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('s', 'Saturday'), ('su', 'Sunday')], default='d', help_text='Days availability', max_length=2),
        ),
    ]
