# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0016_auto_20170509_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutschedule',
            options={'ordering': ['-name_of_client']},
        ),
        migrations.RenameField(
            model_name='weightin',
            old_name='client_pk',
            new_name='name_of_client',
        ),
        migrations.RenameField(
            model_name='workoutschedule',
            old_name='client_pk',
            new_name='name_of_client',
        ),
        migrations.AlterField(
            model_name='workoutschedule',
            name='schedule',
            field=models.CharField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('s', 'Saturday'), ('su', 'Sunday')], help_text='Days availability', max_length=2),
        ),
    ]
