# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0017_auto_20170509_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutschedule',
            options={},
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='date_WO',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workoutschedule',
            name='schedule',
            field=models.CharField(choices=[('m', 'Monday'), ('t', 'Tuesday'), ('w', 'Wednesday'), ('th', 'Thursday'), ('f', 'Friday'), ('s', 'Saturday'), ('su', 'Sunday')], default='m', help_text='Day of week availability', max_length=2),
        ),
    ]
