# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0018_auto_20170509_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='schedule',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', help_text='Day of week availability', max_length=30),
        ),
    ]
